spring.application.name=cortaai-ms-client-springboot

spring.datasource.url=jdbc:postgresql://localhost:5432/cortaai
spring.datasource.username=admin
spring.datasource.password=senha123

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Feign - Auth Service Config
auth-service.url=http://localhost:8002